---
version: '2'
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      




# docker run -d -p 9092:9092 \
# -e KAFKA_ZOOKEEPER_CONNECT=192.168.1.5:2181 \
# -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.5:9092 \
# -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
# confluentinc/cp-kafka